[lib]

[package]
name = "tdf-engine"
version = "0.0.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
serde = { version = "1.0.228", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["constructor"] }
